from SARAGSNP.AttentiveLayers import Fingerprint
from SARAGSNP.AttentiveLayers_viz import Fingerprint_viz
from SARAGSNP.getFeatures import save_smiles_dicts, get_smiles_dicts, get_smiles_array, moltosvg_highlight